### ISSUE TITLE
字符微信二维码无法扫描

### ISSUE THREAD

**Issue by langleegelang** [yaphone/RasWxNeteaseMusic#11]
生成微信二维码后，我把二维码粘贴到windows自带的记事本中，粘贴后的二维码无法扫描。（粘贴后会显示正方形的二维码，以解决终端中二维码字符宽度问题。）

在你之前的回答中提到的打开QR.jpg的方法是可行的，只是比较好奇为什么二维码都正方形了，还是无法扫描

**Comment by yaphone** [comment]
嗯  那可以直接扫描生成的二维码图片。
不过目前网易云音乐的API好像有些问题，树莓派不知道让我放哪了，还没来得及修复。。。
