### ISSUE TITLE
BUG 登录

### ISSUE THREAD

**Issue by DeadlineSurvivor** [yaphone/RasWxNeteaseMusic#2]
我对比了 两个版本的myapi.py 发现此版本的 login函数内 password参数加密 缺少编码 我不知道 作者是不是有意为之

**Comment by yaphone** [comment]
谢谢反馈，电脑版本需要考虑Windows平台（GBK编码），故做了转码处理，树莓派(Raspbian)为utf8编码，测试无需转码，如有使用问题，欢迎再次反馈。
